[inicio]
[setup]
json=
PbAutobuildPath = C:\Program Files (x86)\Appeon\PowerBuilderUtilities 22.0

[powerclient.json]
version_control=S
GitHubProfileName = rasanfe
ProfileVisibility = Public
PersonalToken = 
GitHubRepository = Reports_PowerServer
GitBranch = main
Pbl = reports.pbl
filename = powerclient.srj
DBMS = 
LogPass =
ServerName = 
LogId = 
AutoCommit = 
DBParm = 

[powerserver.json]
PowerServerPath=C:\inetpub\wwwroot\powerserver
UserName = 
UserPass = 
version_control=S
GitHubProfileName = rasanfe
ProfileVisibility = Public
PersonalToken = 
GitHubRepository = Reports_PowerServer
GitBranch = main
Pbl = reports.pbl
filename = powerserver.srj
Scope =serverapi
Name = 
GivenName = 
FamilyName = 
WebSite = 
Email =  
EmailVerified = 

[pbnative.json]
PBNativePath=
version_control=S
GitHubProfileName = rasanfe
ProfileVisibility = Public
PersonalToken = 
GitHubRepository = Reports_PowerServer
GitBranch = main
Pbl = reports.pbl
filename = pbnative.srj
DBMS = 
LogPass =
ServerName = 
LogId = 
AutoCommit = 
DBParm = 


